### ISSUE TITLE
The browser extension doesn't know rummager has been killed

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-browser-extension#124]
We renamed rummager to search-api but the extension thinks rummager still exists.

![Screen Shot 2019-05-16 at 10 31 47 (2)](https://user-images.githubusercontent.com/23193154/57843311-ebcf3a00-77c5-11e9-984b-716e293f4dd4.png)

**Comment by tijmenb** [comment]
This was fixed in https://github.com/alphagov/search-api/pull/1518.
