### ISSUE TITLE
Link to Firefox addon broken

### ISSUE THREAD

**Issue by selfthinker** [alphagov/govuk-browser-extension#150]
The link to the [Firefox addon](https://addons.mozilla.org/en-GB/firefox/addon/govuk-browser-extension/) is broken. It goes to a 404 page. ("Oops! We can’t find that page")
I've searched within addons.mozilla.org and couldn't find it. So, I assume the extension has been removed?
Does anyone know why? And can it be fixed?

I'm aware this can be installed manually, and that's still working.
It just would be nicer and easier if it could be installed via the most common way.

**Comment by alex-ju** [comment]
Thanks for flagging this @selfthinker. It is under our radar – it seem like Mozilla decided to disable out plugin due to lack of description. I have submitted additional info and hope to restore the public URL soon 🤞

**Comment by alex-ju** [comment]
The Firefox addon URL works again now. Will keep the issue open for a while since last time they changed the status from approved to rejected a few weeks after publishing the latest version.
