### ISSUE TITLE
Choosing the Staging environment hangs Firefox when not connected to VPN

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk-browser-extension#155]
#### Steps to reproduce

I'm using Firefox 97.0.1 on macOS 11.6.4 on a GDS-managed laptop (not BYOD).

1. Disconnect from the VPN. If you're in the GDS office, connect to a non-GDS network such as your phone's mobile hotspot.
1. Go to www.gov.uk.
1. Click on the crown logo on the in the address bar (right-hand side).
1. Click "Staging".

#### Expected behaviour

"We're experiencing technical difficulties. Please try again later." error page loads (which is what normally happens when trying to access www.staging.publishing.service.gov.uk from outside GDS while not on the VPN.

#### Observed behaviour

The extension and the entire browser UI become unresponsive. The rainbow-coloured "beachball" cursor appears.

**Comment by KludgeKML** [comment]
@sengi I believe this has fixed itself (ie works as expected on the current version of Firefox), could you confirm?

**Comment by sengi** [comment]
Ooh, indeed it has! I can no longer reproduce the problem. (I'm currently on Firefox 111.0b4.)

Thanks for looking into this!
