### ISSUE TITLE
'SmartAnswers: Display GovSpeak' option not working

### ISSUE THREAD

**Issue by MartinJJones** [alphagov/govuk-browser-extension#163]
The 'SmartAnswers: Display GovSpeak' option is not working in the govuk browser extension.

To reproduce this error, please follow the steps below:

- Visit https://www.gov.uk/check-uk-visa/y/afghanistan/tourism
- Click on 'SmartAnswers: Display GovSpeak' from the govuk browser extension dropdown menu
- ".txt" is appended to the URL
- An error message is shown

![gov uk_chrome_extension_options_for_smart_answers](https://user-images.githubusercontent.com/28779939/220317319-405e5eba-3c39-43f8-ad7c-b5441c3be786.png)

**Comment by KludgeKML** [comment]
https://trello.com/c/lcZjfxq8/1838-remove-unused-display-govspeak-option-from-govuk-browser-extension

**Comment by KludgeKML** [comment]
Content team confirm that they don't use this feature.
