### ISSUE TITLE
Firefox compatibility since V3 migration

### ISSUE THREAD

**Issue by yndajas** [alphagov/govuk-browser-extension#210]
See https://github.com/alphagov/govuk-browser-extension/pull/209 and the links therein

tl;dr `background.service_worker` is currently unsupported in V3 manifests in Firefox, so you have to delete the `background` section to get the extension to function, but the icon change on GOV.UK domains won't happen

**Comment by ChrisBAshton** [comment]
Fixed in #214, #215 and #216.
