### ISSUE TITLE
Highlight components feature should only appear on www.gov.uk

### ISSUE THREAD

**Issue by tijmenb** [alphagov/govuk-browser-extension#85]
This extension works on content pages (www.gov.uk/*) and *.publishing.service.gov.uk domains. On the latter we shouldn't show the highlight components feature (https://github.com/alphagov/govuk-toolkit-chrome/pull/79) because it wouldn't do anything:

![screen shot 2017-10-05 at 08 49 10](https://user-images.githubusercontent.com/233676/31216047-06552844-a9aa-11e7-8841-fa5464752226.png)

**Comment by rubenarakelyan** [comment]
This logic would also break the feature on non-production environments. Is there a good way to differentiate between backend apps and non-production frontend apps? Maybe look for `www` or `www-origin`?

**Comment by tijmenb** [comment]
I think we do that here: 

https://github.com/alphagov/govuk-toolkit-chrome/blob/ac49f9df63c521aa48373c5e8dacd3c8fc6831a0/src/popup/environment.js#L59

**Comment by tijmenb** [comment]
We shouldn't do this anymore, because one day we'll use the components in the backend too! Closing.
